"""initial tables

Revision ID: 0c83079959b9
Revises: 
Create Date: 2026-03-28 19:30:53.435134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c83079959b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clothing_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('TOP', 'BOTTOM', 'OUTERWEAR', 'DRESS', 'SHOES', 'ACCESSORY', 'OTHER', name='clothingcategory'), nullable=False),
    sa.Column('color_primary', sa.String(length=50), nullable=True),
    sa.Column('color_secondary', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('season', sa.Enum('SPRING', 'SUMMER', 'FALL', 'WINTER', 'ALL', name='season'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('original_image_url', sa.String(length=512), nullable=False),
    sa.Column('cleaned_image_url', sa.String(length=512), nullable=True),
    sa.Column('style_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('preview_image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outfit_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outfit_id', sa.UUID(), nullable=False),
    sa.Column('clothing_item_id', sa.UUID(), nullable=False),
    sa.Column('layer_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfit_items')
    op.drop_table('outfits')
    op.drop_table('clothing_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
