// Generated by FlutterFire CLI — run `flutterfire configure` to regenerate
// with your iOS and Android specific values.
//
// !! You MUST run `flutterfire configure` before this app will work !!
// See README for setup instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('DefaultFirebaseOptions not configured for this platform.');
    }
  }

  // Web config — already filled in from Firebase Console
  static const web = FirebaseOptions(
    apiKey: 'AIzaSyDVAVzJVNnJSskwvgDURJ-waiK3XSJLaRs',
    authDomain: 'closeteye-c2c03.firebaseapp.com',
    projectId: 'closeteye-c2c03',
    storageBucket: 'closeteye-c2c03.firebasestorage.app',
    messagingSenderId: '877575008426',
    appId: '1:877575008426:web:02eba8f204c1ce01fca0d3',
    measurementId: 'G-CWXNT2Y6DW',
  );

  // iOS — values from GoogleService-Info.plist
  static const ios = FirebaseOptions(
    apiKey: 'AIzaSyAG_q8nyht84J3w8dtGTCColCf3p7c1pFA',
    appId: '1:877575008426:ios:c9f0706012f3248ffca0d3',
    messagingSenderId: '877575008426',
    projectId: 'closeteye-c2c03',
    storageBucket: 'closeteye-c2c03.firebasestorage.app',
    iosBundleId: 'com.closeteye.closeteye',
  );

  // Android — filled in by `flutterfire configure` after you add Android app in Firebase Console
  static const android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: '877575008426',
    projectId: 'closeteye-c2c03',
    storageBucket: 'closeteye-c2c03.firebasestorage.app',
  );
}
